using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Navigation;
using Autodesk.Revit.UI;
using PlanUp.Engine;

namespace PlanUp.UI
{
    /// <summary>
    /// The WPF panel that displays compliance check results inside Revit.
    /// 
    /// This class does three things:
    /// 
    /// 1. Implements IDockablePaneProvider, which is the Revit interface that
    ///    tells Revit "I am a panel that can be docked alongside the model view."
    ///    Without this interface, Revit would not know how to host our WPF control.
    /// 
    /// 2. Provides the SetupDockablePane method where we configure the initial
    ///    docking position (right side, like the Properties panel).
    /// 
    /// 3. Provides the LoadResults method that takes a list of CheckResult objects
    ///    and displays them in the panel with traffic light colors.
    /// 
    /// HOW DOCKABLE PANES WORK IN REVIT:
    /// 
    ///   - In PlanUpApp.OnStartup, we call RegisterDockablePane with a unique GUID,
    ///     a title string, and an instance of this class.
    ///   - Revit stores the pane but does not show it yet.
    ///   - When RunCheckCommand executes, it calls DockablePane.Show() to make
    ///     the pane visible, then calls our LoadResults method to fill it with data.
    ///   - The user can then dock it, float it, or close it like any Revit panel.
    /// </summary>
    public partial class CompliancePanel : UserControl, IDockablePaneProvider
    {
        /// <summary>
        /// Constructor. InitializeComponent() is auto generated by the XAML compiler.
        /// It reads CompliancePanel.xaml and creates all the UI elements defined there.
        /// </summary>
        public CompliancePanel()
        {
            InitializeComponent();
        }

        /// <summary>
        /// Called by Revit when registering this pane. We configure the initial state here.
        /// 
        /// DockPosition options:
        ///   Tabbed  = appears as a tab alongside other panels (like Properties + Project Browser)
        ///   Left    = docks to the left edge
        ///   Right   = docks to the right edge
        ///   Top     = docks to the top
        ///   Bottom  = docks to the bottom
        ///   Floating = opens as a floating window
        /// 
        /// We use Right because that is where architects typically have the Properties panel,
        /// and compliance results are contextual information about the model, similar to properties.
        /// </summary>
        public void SetupDockablePane(DockablePaneProviderData data)
        {
            data.FrameworkElement = this;
            data.InitialState = new DockablePaneState
            {
                DockPosition = DockPosition.Right
            };
        }

        /// <summary>
        /// Takes a list of CheckResult objects and displays them in the panel.
        /// 
        /// This method:
        ///   1. Hides the placeholder text ("Press Run Check...")
        ///   2. Shows the summary bar with green/yellow/red counts
        ///   3. Binds the results list to the ItemsControl in the XAML
        /// 
        /// DATA BINDING EXPLAINED:
        /// When we set ResultsList.ItemsSource = results, WPF automatically
        /// loops through the list and creates one visual item (defined by the
        /// DataTemplate in the XAML) for each CheckResult. The {Binding RuleName}
        /// expressions in the XAML pull values from each CheckResult object.
        /// This is why the property names in CheckResult.cs must match exactly
        /// what the XAML references.
        /// </summary>
        public void LoadResults(List<CheckResult> results)
        {
            PlaceholderText.Visibility = Visibility.Collapsed;

            // Sort: red first, then yellow, then green
            var sorted = results
                .OrderByDescending(r => r.Status == ComplianceStatus.Red ? 2 :
                    r.Status == ComplianceStatus.Yellow ? 1 : 0)
                .ToList();

            SummaryBar.Visibility = Visibility.Visible;
            GreenCount.Text = sorted.Count(r => r.Status == ComplianceStatus.Green).ToString();
            YellowCount.Text = sorted.Count(r => r.Status == ComplianceStatus.Yellow).ToString();
            RedCount.Text = sorted.Count(r => r.Status == ComplianceStatus.Red).ToString();

            ResultsList.ItemsSource = sorted;
        }

        /// <summary>
        /// Clears all results and shows the placeholder text again.
        /// Useful when the user opens a different project.
        /// </summary>
        public void ClearResults()
        {
            PlaceholderText.Visibility = Visibility.Visible;
            SummaryBar.Visibility = Visibility.Collapsed;
            ResultsList.ItemsSource = null;
        }

        /// <summary>
        /// Handles clicking on an article reference hyperlink.
        /// Opens the source URL in the user's default web browser.
        /// </summary>
        private void Hyperlink_RequestNavigate(object sender, RequestNavigateEventArgs e)
        {
            if (!string.IsNullOrEmpty(e.Uri?.AbsoluteUri))
            {
                Process.Start(new ProcessStartInfo
                {
                    FileName = e.Uri.AbsoluteUri,
                    UseShellExecute = true
                });
            }
            e.Handled = true;
        }
    }

    /// <summary>
    /// A VALUE CONVERTER for WPF.
    /// 
    /// The XAML needs to hide the DetailDescription TextBlock when it is empty.
    /// WPF cannot do "if string is empty, hide this element" directly in XAML.
    /// Instead, we write a converter class that translates a string value into
    /// a Visibility value:
    ///   - non empty string = Visible
    ///   - empty or null string = Collapsed (hidden, takes no space)
    /// 
    /// The XAML references this converter by name:
    ///   Visibility="{Binding DetailDescription, Converter={StaticResource StringToVisibilityConverter}}"
    /// 
    /// IValueConverter is a WPF interface with two methods:
    ///   Convert     = data to UI (string to Visibility)
    ///   ConvertBack = UI to data (not needed here, so we throw an exception)
    /// </summary>
    public class StringToVisibilityConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            string text = value as string;
            return string.IsNullOrWhiteSpace(text) ? Visibility.Collapsed : Visibility.Visible;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}
